version: "3.8"

services:
  api:
    build: .
    container_name: nation-sounds-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    volumes:
      - ./uploads:/app/uploads
